import { IProduct } from '../../products/interfaces/product.interface';

export const productSeed: IProduct[] = [
  {
    _id: '63003a288c5932b985e5de70',
    code: 'YODUGL1K',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/354766/',
    name: 'Yogurt',
    price: 4.5,
    description: 'Yogurt Parcialmente Descremado Durazno Gloria Botella 1 kg',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {} as any,
      userUpdate: null,
      activeRecord: true,
    },
  },
  {
    _id: '63003a288c5932b985e5de71',
    code: 'ATUFLO1G',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/535795/',
    name: 'Atun',
    price: 7.5,
    description: 'Filete de Atún en Aceite Florida 150g',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {},
      userUpdate: null,
      activeRecord: true,
    },
  },
  {
    _id: '63003a288c5932b985e5de72',
    code: 'ATUNIC1G',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/545828/',
    name: 'Atun',
    price: 5.5,
    description: 'Filete de Atún Nicolini 160g',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {},
      userUpdate: null,
      activeRecord: true,
    },
  },
  {
    _id: '63003a288c5932b985e5de73',
    code: 'PASMOL5G',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/492463/',
    name: 'Pasta',
    price: 10.5,
    description: 'Pasta Corta Macarrón Bolsa 500 g',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {},
      userUpdate: null,
      activeRecord: true,
    },
  },
  {
    _id: '63003a288c5932b985e5de74',
    code: 'PASVIT5G',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/352252/',
    name: 'Pasta',
    price: 3.5,
    description: 'Pasta de Trigo Tornillo Don Vittorio Bolsa 500 gr',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {},
      userUpdate: null,
      activeRecord: true,
    },
  },
  {
    _id: '63003a288c5932b985e5de75',
    code: 'AVNQUA2G',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/215276/',
    name: 'Avena',
    price: 3.5,
    description: 'Avena Tradicional Quaker 200 g',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {},
      userUpdate: null,
      activeRecord: true,
    },
  },
  {
    _id: '63003a288c5932b985e5de76',
    code: 'AVNOSI9G',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/550692/',
    name: 'Avena',
    price: 6.5,
    description: 'Avena Precocida 3 Ositos 900g',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {},
      userUpdate: null,
      activeRecord: true,
    },
  },
  {
    _id: '63003a288c5932b985e5de77',
    code: 'ARRFAR5K',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/215276/',
    name: 'Arroz',
    price: 7.5,
    description: 'Arroz Faraon Extra Añejo Naranja Bolsa 5 kg',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {},
      userUpdate: null,
      activeRecord: true,
    },
  },
  {
    _id: '63003a288c5932b985e5de78',
    code: 'ARRCOS5K',
    url: 'https://wongfood.vteximg.com.br/arquivos/ids/254547/',
    name: 'Arroz',
    price: 8.5,
    description: 'Arroz Extra Costeño 5kg',
    status: {
      value: 1,
      description: 'Creado por base de datos',
    },
    auditProperties: {
      dateCreate: new Date(),
      dateUpdate: null,
      userCreate: {},
      userUpdate: null,
      activeRecord: true,
    },
  },
];
